steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aasan-rishte-backend', '-f', 'Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aasan-rishte-backend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'aasan-rishte-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aasan-rishte-backend'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--timeout'
      - '600'
      - '--set-env-vars'
      - 'FRONTEND_URL=https://frontend-228802607375.us-central1.run.app'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'aasan-rishte-469421:asia-south1:matrimonial-db'
      - '--update-secrets=DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest,SMTP_HOST=SMTP_HOST:latest,SMTP_PORT=SMTP_PORT:latest,SMTP_USERNAME=SMTP_USERNAME:latest,SMTP_PASSWORD=SMTP_PASSWORD:latest'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'aasan-rishte-backend-migrate'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aasan-rishte-backend'
      - '--region'
      - 'asia-south1'
      - '--command=poetry'
      - '--args=run,prisma,migrate,deploy'
      - '--service-account'
      - '228802607375-compute@developer.gserviceaccount.com'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest'
      - '--add-cloudsql-instances'
      - 'aasan-rishte-469421:asia-south1:matrimonial-db'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - 'aasan-rishte-backend-migrate'
      - '--region'
      - 'asia-south1'
      - '--wait'

images:
  - 'gcr.io/$PROJECT_ID/aasan-rishte-backend'
